"""Codegen: shared/schemas/strategy.spec.json -> web/src/generated/enums.ts.

Single-source enums for the frontend. Strategy validation stays server-side
(jsonschema against this same file); the web renders forms from API-served
param schemas and never re-validates strategies client-side.
CI asserts freshness: regenerate and `git diff --exit-code`.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SCHEMA = ROOT / "shared" / "schemas" / "strategy.spec.json"
DEST = ROOT / "web" / "src" / "generated" / "enums.ts"


def _ts(name: str, values: list[str]) -> str:
    items = "\n".join(f'  "{v}",' for v in values)
    return f"export const {name} = [\n{items}\n] as const;"


def main() -> None:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    props = schema["properties"]
    universe = props["universe"]["properties"]
    entry = props["entry"]["properties"]
    defs = schema["$defs"]
    indicator_kinds = ["EMA", "SMA", "RSI", "ATR", "MACD", "BB", "ADX", "Donchian", "VWAP"]
    ops = defs["condition"]["properties"]["op"]["enum"]
    price_fields = ["open", "high", "low", "close"]
    exit_kinds = ["atr", "pips", "rr", "none"]
    out = "\n".join(
        [
            "// GENERATED by backend/scripts/codegen.py — do not edit.",
            _ts("SYMBOLS", universe["symbol"]["enum"]),
            _ts("TIMEFRAMES", universe["timeframe"]["enum"]),
            _ts("DIRECTIONS", entry["direction"]["enum"]),
            _ts("LOGIC", entry["logic"]["enum"]),
            _ts("CONDITION_OPS", ops),
            _ts("PRICE_FIELDS", price_fields),
            _ts("INDICATOR_KINDS", indicator_kinds),
            _ts("EXIT_KINDS", exit_kinds),
            "",
        ]
    )
    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(out, encoding="utf-8")
    print(f"wrote {DEST}")


if __name__ == "__main__":
    main()
